name: build_push_docker_artifact_registry
description: Build and push a Docker image to Google Cloud Artifact Registry

inputs:
  gcp_credentials_json:
    description: "Google Cloud Service Account JSON, it is recommended to feed this with a GitHub secret value."
    required: true

  docker_target:
    description: "Docker target stage."
    required: true
  
  env_str:
    description: "Comma-separated key-value pairs that will be exported in docker build-args command."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Parse and Build env exports
      run: |
        combined_args="${{ inputs.combined_args }}"

        # Split the string into an array, using commas as the delimiter
        IFS=',' read -r -a args_array <<< "$combined_args"

        build_args=""

        # Iterate over the array and append each key-value pair to build_args
        for arg in "${args_array[@]}"; do
          build_args="$build_args $arg"
        done

        echo "build_args=$build_args" >> $GITHUB_ENV
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials_json }}
    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        target: ${{ inputs.docker_target }}
        push: true
        build-args: ${{ env.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ inputs.tags }}