name: build-push-docker-gcp-artifact-registry-action
description: Build and push a Docker image to Google Cloud Artifact Registry

inputs:
  gcp_credentials_json:
    description: "Google Cloud Service Account JSON, it is recommended to feed this with a GitHub secret value."
    required: true

  docker_target:
    description: "Docker target stage."
    required: true

  tags:
    description: "Docker image tags"
    required: true
  
  build_args:
    description: "Key-value pairs that will be exported in docker build-args command."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials_json }}
    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        target: ${{ inputs.docker_target }}
        push: true
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ inputs.tags }}
